/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatArea: typeof import('./src/components/chat/ChatArea.vue')['default']
    ChatContainer: typeof import('./src/components/chat/ChatContainer.vue')['default']
    ConversationList: typeof import('./src/components/chat/ConversationList.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeScreen: typeof import('./src/components/chat/WelcomeScreen.vue')['default']
  }
}
